//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class APP_LOGERROR
    {
        public long SECUENCIA { get; set; }
        public string PROCESO { get; set; }
        public string ERROR { get; set; }
        public System.DateTime FECHA { get; set; }
        public string INNER { get; set; }
    }
}
