//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARINDEX
    {
        public string DATA { get; set; }
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string ESTADO { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<decimal> CONTROL_FACTURAS { get; set; }
        public string DIRECCION { get; set; }
        public string TELEFONOS { get; set; }
        public Nullable<decimal> TIPO_COMISION { get; set; }
        public string PADRE { get; set; }
        public Nullable<System.DateTime> FECHA_INGRESO { get; set; }
        public Nullable<System.DateTime> FECHA_SALIDA { get; set; }
        public Nullable<decimal> CUENTA { get; set; }
        public string CEDULA { get; set; }
        public string REFERENCIA { get; set; }
        public short EMPRESA { get; set; }
        public string COD_UND_CAE { get; set; }
    }
}
