//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ARPROVEEDOR
    {
        public string CODIGO { get; set; }
        public string NOMBRE { get; set; }
        public string CEDULA { get; set; }
        public string RUC { get; set; }
        public string DOMICILIO { get; set; }
        public string TELEFONOS { get; set; }
        public string DATA { get; set; }
        public string CIUDAD { get; set; }
        public Nullable<System.DateTime> FECHA_ULTMOD { get; set; }
        public Nullable<System.DateTime> FEC_APERTURA { get; set; }
        public string ESTADO { get; set; }
        public Nullable<System.DateTime> FECHA_STATUS { get; set; }
        public Nullable<System.DateTime> FEC_ULTCOMP { get; set; }
        public string EXENTO_IVA { get; set; }
        public string APELLIDO { get; set; }
        public string COMENTARIO { get; set; }
        public Nullable<decimal> SALDO_COMPRAS { get; set; }
        public Nullable<decimal> CUPO_COMPRAS { get; set; }
        public Nullable<decimal> CUPOMES_COMPRAS { get; set; }
        public Nullable<decimal> DESCUENTO { get; set; }
        public Nullable<long> CODIGO_NUM { get; set; }
        public string CODIGO1 { get; set; }
        public Nullable<decimal> SALDOD_COMPRAS { get; set; }
        public string STATUS { get; set; }
        public string PAIS { get; set; }
        public string CTACONTABLE { get; set; }
        public string DATAZO { get; set; }
        public string CODIGOZO { get; set; }
        public string E_MAIL { get; set; }
        public string CONTACTO { get; set; }
    }
}
