//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAB_BITACORA
    {
        public int ID { get; set; }
        public string VIAJE { get; set; }
        public string DATA_VIAJE { get; set; }
        public Nullable<System.DateTime> FECINGRESO { get; set; }
        public string BARCO { get; set; }
        public string LOGIN { get; set; }
        public string ESTADO { get; set; }
        public Nullable<short> EMPRESA { get; set; }
    }
}
