//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAB_BITACORA_PARAM
    {
        public decimal ID { get; set; }
        public decimal OP1_INICIO { get; set; }
        public decimal OP1_FIN { get; set; }
        public decimal OP1_PREMIO { get; set; }
        public decimal OP1_MULTA { get; set; }
        public decimal OP2_INICIO { get; set; }
        public decimal OP2_FIN { get; set; }
        public decimal OP2_PREMIO { get; set; }
        public decimal OP3_VERDE { get; set; }
        public decimal OP3_AZUL { get; set; }
        public decimal OP4_COMISION { get; set; }
        public decimal OP3_TOTAL { get; set; }
        public Nullable<decimal> OP3_ROJO { get; set; }
    }
}
