//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CAB_BITACORA_PARAM_OP4
    {
        public decimal ID { get; set; }
        public decimal LINEA { get; set; }
        public Nullable<decimal> OP4_INI { get; set; }
        public Nullable<decimal> OP4_FIN { get; set; }
        public Nullable<decimal> OP4_POR { get; set; }
        public Nullable<decimal> OP4_VALOR { get; set; }
    }
}
