//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class DET_BITACORA
    {
        public int ID { get; set; }
        public short LINEA { get; set; }
        public string DESCRIPCION { get; set; }
        public string CONTRATISTA { get; set; }
        public Nullable<short> EMPRESA { get; set; }
        public Nullable<short> ST_EMPLEADO { get; set; }
        public string LINEA_STCUMPLI1 { get; set; }
        public string LINEA_STCUMPLI2 { get; set; }
        public string LINEA_LOGINCUMPLI1 { get; set; }
        public string LINEA_LOGINCUMPLI2 { get; set; }
        public Nullable<System.DateTime> LINEA_FECCUMPLI1 { get; set; }
        public Nullable<System.DateTime> LINEA_FECCUMPLI2 { get; set; }
    }
}
