//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesGeneral : DbContext
    {
        public EntitiesGeneral()
            : base("name=EntitiesGeneral")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<TBCINV> TBCINV { get; set; }
        public DbSet<TBCINV_APPCORREOS> TBCINV_APPCORREOS { get; set; }
        public DbSet<TBDINV> TBDINV { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<VW_ORDENES_TRABAJO> VW_ORDENES_TRABAJO { get; set; }
        public DbSet<VW_ORDENES_TRABAJO_TOTAL> VW_ORDENES_TRABAJO_TOTAL { get; set; }
    }
}
