//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EntitiesGeneral : DbContext
    {
        public EntitiesGeneral()
            : base("name=EntitiesGeneral")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<CAB_BITACORA> CAB_BITACORA { get; set; }
        public DbSet<DET_BITACORA> DET_BITACORA { get; set; }
        public DbSet<DET_BITACORA2> DET_BITACORA2 { get; set; }
        public DbSet<TBCINV> TBCINV { get; set; }
        public DbSet<TBCINV_APPCORREOS> TBCINV_APPCORREOS { get; set; }
        public DbSet<TBDINV> TBDINV { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<VW_BITACORAS> VW_BITACORAS { get; set; }
        public DbSet<VW_ORDENES_TRABAJO_APP> VW_ORDENES_TRABAJO_APP { get; set; }
        public DbSet<VW_ORDENES_TRABAJO_TOTAL_APP> VW_ORDENES_TRABAJO_TOTAL_APP { get; set; }
        public DbSet<ARINDEX> ARINDEX { get; set; }
        public DbSet<SUCURSAL> SUCURSAL { get; set; }
    }
}
