//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBBI_SECDOC
    {
        public short DOC_CIA { get; set; }
        public string DOC_BOD { get; set; }
        public string DOC_SGL { get; set; }
        public int DOC_NUM { get; set; }
        public string DOC_TIPO { get; set; }
    }
}
