//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCINV_APP_ORDENES_SALTADAS
    {
        public int ID { get; set; }
        public string USUARIO { get; set; }
        public string CINV_TDOC { get; set; }
        public int CINV_NUM { get; set; }
    }
}
