//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCINV_APPCORREOS
    {
        public string CINV_TDOC { get; set; }
        public int CINV_NUM { get; set; }
        public string CINV_LOGIN { get; set; }
        public string CINV_ST { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_APRO { get; set; }
        public string COMENTARIO { get; set; }
        public string ROL_APRO { get; set; }
        public int SECUENCIAL { get; set; }
    }
}
