//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCINV
    {
        public int CINV_SEC { get; set; }
        public string CINV_TDOC { get; set; }
        public int CINV_NUM { get; set; }
        public string CINV_BOD { get; set; }
        public string CINV_TBOD { get; set; }
        public string CINV_REF { get; set; }
        public System.DateTime CINV_FECING { get; set; }
        public string CINV_ID { get; set; }
        public string CINV_NOMID { get; set; }
        public Nullable<decimal> CINV_DSC { get; set; }
        public string CINV_COM1 { get; set; }
        public string CINV_COM2 { get; set; }
        public string CINV_COM3 { get; set; }
        public string CINV_COM4 { get; set; }
        public decimal CINV_TASA { get; set; }
        public string CINV_LOGIN { get; set; }
        public string CINV_TDIV { get; set; }
        public string CINV_ST { get; set; }
        public short EMPRESA { get; set; }
        public string DATATR { get; set; }
        public string CODIGOTR { get; set; }
        public string CINV_NOTA { get; set; }
        public string CINV_FPAGO { get; set; }
        public Nullable<System.DateTime> CINV_HORA { get; set; }
        public Nullable<short> CINV_TIPRECIO { get; set; }
        public Nullable<System.DateTime> CINV_FECAPRUEBA { get; set; }
        public Nullable<System.DateTime> CINV_FECLLEGADA { get; set; }
        public Nullable<System.DateTime> CINV_FECEMBARQUE { get; set; }
        public Nullable<System.DateTime> CINV_FECDESADUA { get; set; }
        public string CINV_MOTIVOANULA { get; set; }
        public Nullable<int> CINV_PROVISION { get; set; }
        public string CINV_COM5 { get; set; }
        public string CINV_COM6 { get; set; }
        public string CINV_COM7 { get; set; }
        public string CINV_DETAPAGO { get; set; }
        public string CINV_STCUMPLI1 { get; set; }
        public string CINV_COMENCUMPLI1 { get; set; }
        public string CINV_STCUMPLI2 { get; set; }
        public string CINV_COMENCUMPLI2 { get; set; }
        public Nullable<System.DateTime> CINV_FECCUMPLI1 { get; set; }
        public Nullable<System.DateTime> CINV_FECCUMPLI2 { get; set; }
        public string CINV_LOGINCUMPLI1 { get; set; }
        public string CINV_LOGINCUMPLI2 { get; set; }
        public Nullable<decimal> DURACION { get; set; }
    }
}
