//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCPED
    {
        public decimal PED_ID { get; set; }
        public Nullable<System.DateTime> PED_FECHA { get; set; }
        public string PED_BOD { get; set; }
        public string PED_VIAJE { get; set; }
        public string PED_SUC { get; set; }
        public string PED_SOL { get; set; }
        public string PED_OBS { get; set; }
        public string PED_ST { get; set; }
        public Nullable<System.DateTime> OC_FECHA { get; set; }
        public Nullable<System.DateTime> INV_FECHA { get; set; }
        public string PED_LOGIN { get; set; }
        public Nullable<System.DateTime> PED_FECTRAN { get; set; }
        public string PED_COM { get; set; }
        public Nullable<System.DateTime> PED_FECAPRO { get; set; }
    }
}
