//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBDPED
    {
        public decimal PED_ID { get; set; }
        public decimal PED_SEC { get; set; }
        public Nullable<decimal> PED_CANT { get; set; }
        public string PED_DETALLE { get; set; }
    }
}
