//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBNOM_EMPLEADO
    {
        public short EMPL_EMPR { get; set; }
        public string EMPL_CO { get; set; }
        public string EMPL_AP { get; set; }
        public string EMPL_NO { get; set; }
        public long TIPO_TRAB_CO { get; set; }
        public System.DateTime EMPL_FEINGR { get; set; }
        public decimal EMPL_SLBASICO { get; set; }
        public decimal EMPL_VAHORA { get; set; }
        public Nullable<decimal> EMPL_HRPROD { get; set; }
        public string CARGO_CO { get; set; }
        public string DEPAR_CO { get; set; }
        public string DEPAR_CO_RESIDE { get; set; }
        public Nullable<System.DateTime> EMPL_FENACE { get; set; }
        public string EMPL_NUCEDU { get; set; }
        public string EMPL_LIC { get; set; }
        public string EMPL_NUPASAPORTE { get; set; }
        public string EMPL_LIB_MILITAR { get; set; }
        public string EMPL_NU_AFILIA { get; set; }
        public string EMPL_SEXO { get; set; }
        public long TIPO_SANG_TI { get; set; }
        public string TIPO_SANG_CO { get; set; }
        public Nullable<decimal> EMPL_ESTATURA { get; set; }
        public Nullable<decimal> EMPL_PESO { get; set; }
        public string EMPL_DR { get; set; }
        public string EMPL_FO { get; set; }
        public long ESTA_CIVIL_TI { get; set; }
        public string ESTA_CIVIL_CO { get; set; }
        public string EMPL_CONYUGE { get; set; }
        public string EMPL_NUCTA { get; set; }
        public string EMPL_NUCTACTE { get; set; }
        public Nullable<System.DateTime> EMPL_FEFINCON { get; set; }
        public string EMPL_ULTRAB { get; set; }
        public Nullable<System.DateTime> EMPL_FEINIVAC { get; set; }
        public Nullable<System.DateTime> EMPL_FEFINVAC { get; set; }
        public Nullable<System.DateTime> EMPL_FEULTRAB { get; set; }
        public string EMPL_MOULTRAB { get; set; }
        public Nullable<System.DateTime> EMPL_FESALE { get; set; }
        public Nullable<System.DateTime> EMPL_FEVACA_AUM { get; set; }
        public string EMPL_STVACA { get; set; }
        public Nullable<decimal> EMPL_DIAS_REAL { get; set; }
        public Nullable<decimal> EMPL_DEC_SEXTO { get; set; }
        public string EMPL_STFIJO { get; set; }
        public Nullable<long> EMPL_TIEMPO_SEG_MED { get; set; }
        public Nullable<decimal> EMPL_SEG_MED { get; set; }
        public Nullable<decimal> EMPL_PORC_SEG_MED { get; set; }
        public Nullable<decimal> EMPL_ANTI_PARCIAL { get; set; }
        public Nullable<decimal> EMPL_BECA { get; set; }
        public Nullable<decimal> EMPL_BONO { get; set; }
        public Nullable<decimal> EMPL_COMEDOR { get; set; }
        public Nullable<decimal> EMPL_PORC_COMEDOR { get; set; }
        public Nullable<decimal> EMPL_TRANS { get; set; }
        public string EMPL_ST { get; set; }
        public Nullable<decimal> EMPL_TI_CAMBIO { get; set; }
        public string EMPL_MONEDA { get; set; }
        public Nullable<decimal> EMPL_BONI_VOLUN { get; set; }
        public string EMPL_COMOTI_MASTERLE { get; set; }
        public Nullable<long> EMPL_TIMOTI_MASTERLE { get; set; }
        public string EMPL_OCUPACION { get; set; }
        public string EMPL_COMOTI_SALE { get; set; }
        public Nullable<long> EMPL_TIMOTI_SALE { get; set; }
        public Nullable<long> EMPL_HORAENTTI { get; set; }
        public string EMPL_HORAENTCO { get; set; }
        public Nullable<decimal> EMPL_VA_UTILIDAD { get; set; }
        public string EMPL_VA_MOI { get; set; }
        public string EMPL_BANCO { get; set; }
        public string EMPL_COMENTARIO { get; set; }
        public string EMPL_SUCURSAL_CO { get; set; }
        public string EMPL_STFONDORES { get; set; }
        public Nullable<decimal> EMPL_PREST_QUIR { get; set; }
        public Nullable<decimal> EMPL_CELULAR { get; set; }
    }
}
