//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBNOM_ORDEN_NOMINA_CAB
    {
        public int CINV_SEC { get; set; }
        public string CINV_TDOC { get; set; }
        public int CINV_NUM { get; set; }
        public string CINV_BOD { get; set; }
        public string CINV_TBOD { get; set; }
        public string CINV_REF { get; set; }
        public System.DateTime CINV_FECING { get; set; }
        public string CINV_ID { get; set; }
        public string CINV_NOMID { get; set; }
        public Nullable<decimal> CINV_DSC { get; set; }
        public string CINV_COM1 { get; set; }
        public string CINV_COM2 { get; set; }
        public string CINV_COM3 { get; set; }
        public string CINV_COM4 { get; set; }
        public decimal CINV_TASA { get; set; }
        public string CINV_LOGIN { get; set; }
        public string CINV_TDIV { get; set; }
        public string CINV_ST { get; set; }
        public short EMPRESA { get; set; }
        public string DATATR { get; set; }
        public string CODIGOTR { get; set; }
        public string CINV_NOTA { get; set; }
        public string CINV_FPAGO { get; set; }
        public Nullable<System.DateTime> CINV_HORA { get; set; }
        public Nullable<short> CINV_TIPRECIO { get; set; }
        public Nullable<System.DateTime> CINV_FECAPRUEBA { get; set; }
        public Nullable<System.DateTime> CINV_FECLLEGADA { get; set; }
        public Nullable<System.DateTime> CINV_FECEMBARQUE { get; set; }
        public Nullable<System.DateTime> CINV_FECDESADUA { get; set; }
        public string CINV_MOTIVOANULA { get; set; }
        public string CINV_STPOLI { get; set; }
        public string CINV_COMPOLI { get; set; }
        public string CINV_STPSICO { get; set; }
        public string CINV_COMPSICO { get; set; }
        public string CINV_STANTE { get; set; }
        public string CINV_COMANTE { get; set; }
        public string CINV_STPERFIL { get; set; }
        public string CINV_COMPERFIL { get; set; }
        public string CINV_COMANTE2 { get; set; }
        public string CINV_STREFER { get; set; }
        public string CINV_COMREFER { get; set; }
        public string CINV_COMREFER2 { get; set; }
    }
}
