//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIOS
    {
        public int CODIGO { get; set; }
        public string CLAVE { get; set; }
        public string USUARIO { get; set; }
        public string NOMBRE { get; set; }
        public decimal P_VENTAS { get; set; }
        public System.DateTime FECHA { get; set; }
        public string OFICREDA { get; set; }
        public string OFICRECO { get; set; }
        public string GERCRE { get; set; }
        public string ROL_APRO { get; set; }
        public string ROL_CODIGO { get; set; }
    }
}
