//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BITACORAS_APP
    {
        public Nullable<short> EMPRESA { get; set; }
        public int ID { get; set; }
        public string VIAJE { get; set; }
        public string NOM_VIAJE { get; set; }
        public Nullable<System.DateTime> FECINGRESO { get; set; }
        public string BARCO { get; set; }
        public string NOM_BARCO { get; set; }
        public string LOGIN { get; set; }
        public string ESTADO { get; set; }
        public Nullable<short> LINEA { get; set; }
        public string DESCRIPCION { get; set; }
        public string CONTRATISTA { get; set; }
        public Nullable<short> LINEA_DETALLE { get; set; }
        public string NUMERO_ORDEN { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<short> CUMPLIMIENTO { get; set; }
        public string CINV_STCUMPLI1 { get; set; }
        public string CINV_STCUMPLI2 { get; set; }
        public string STORDEN { get; set; }
        public string LINEA_STCUMPLI1 { get; set; }
        public string LINEA_STCUMPLI2 { get; set; }
        public Nullable<System.DateTime> LINEA_FECCUMPLI1 { get; set; }
        public Nullable<System.DateTime> LINEA_FECCUMPLI2 { get; set; }
        public Nullable<short> ST_EMPLEADO { get; set; }
        public Nullable<System.DateTime> FECHA_ARRIBO { get; set; }
        public Nullable<System.DateTime> FECHA_ZARPE { get; set; }
        public Nullable<System.DateTime> FECHA_ZARPE_REAL { get; set; }
        public Nullable<decimal> DURACION { get; set; }
        public Nullable<System.DateTime> FECHA_OT { get; set; }
        public string TIPO { get; set; }
        public string CINV_ST { get; set; }
    }
}
