//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_BITACORAS
    {
        public Nullable<short> EMPRESA { get; set; }
        public int ID { get; set; }
        public string VIAJE { get; set; }
        public string NOM_VIAJE { get; set; }
        public Nullable<System.DateTime> FECINGRESO { get; set; }
        public string BARCO { get; set; }
        public string NOM_BARCO { get; set; }
        public string LOGIN { get; set; }
        public string ESTADO { get; set; }
        public short LINEA { get; set; }
        public string DESCRIPCION { get; set; }
        public string CONTRATISTA { get; set; }
        public Nullable<short> LINEA_DETALLE { get; set; }
        public string NUMERO_ORDEN { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public string STCUMPLI1 { get; set; }
        public string STCUMPLI2 { get; set; }
        public string STORDEN { get; set; }
    }
}
