//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_FILTROS_APP
    {
        public string USUARIO { get; set; }
        public string BARCO { get; set; }
        public string VIAJE { get; set; }
        public string SOLICITANTE { get; set; }
        public string BODEGA { get; set; }
        public string NOMBREBARCO { get; set; }
        public string NOMBREVIAJE { get; set; }
        public string NOMBRESOLICITANTE { get; set; }
        public string NOMBREBODEGA { get; set; }
    }
}
