//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AprobacionesApi.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class VW_PRESUPUESTO_APP
    {
        public short EMPRESA { get; set; }
        public string BARCO { get; set; }
        public string VIAJE { get; set; }
        public string DATA_VIAJE { get; set; }
        public string CINV_TDOC { get; set; }
        public Nullable<System.DateTime> FECHA_ULT_MOD { get; set; }
        public decimal PRESUP_OT { get; set; }
        public decimal PRESUP_OC { get; set; }
        public Nullable<decimal> APROBADO { get; set; }
        public Nullable<decimal> PENDIENTE { get; set; }
        public Nullable<decimal> SALDO { get; set; }
    }
}
