//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BODEGAS
    {
        public string BODEGA { get; set; }
        public int NUMERO_ITEM { get; set; }
        public Nullable<System.DateTime> INICIO { get; set; }
        public Nullable<System.DateTime> FIN { get; set; }
        public Nullable<decimal> STOCK { get; set; }
        public Nullable<decimal> COSTO { get; set; }
        public Nullable<decimal> COSTOD { get; set; }
        public short EMPRESA { get; set; }
    }
}
