//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCINV_APP_ORDENES_SALTADAS
    {
        public int ID { get; set; }
        public string USUARIO { get; set; }
        public string CINV_TDOC { get; set; }
        public int CINV_NUM { get; set; }
    }
}
