//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBCINV_APPCORREOS
    {
        public string CINV_TDOC { get; set; }
        public int CINV_NUM { get; set; }
        public string CINV_LOGIN { get; set; }
        public string CINV_ST { get; set; }
        public Nullable<System.DateTime> FECHA_ENVIO { get; set; }
        public Nullable<System.DateTime> FECHA_APRO { get; set; }
        public string COMENTARIO { get; set; }
    }
}
