//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public int CODIGO { get; set; }
        public string CLAVE { get; set; }
        public string USUARIO1 { get; set; }
        public string NOMBRE { get; set; }
        public decimal P_VENTAS { get; set; }
        public System.DateTime FECHA { get; set; }
        public string OFICREDA { get; set; }
        public string OFICRECO { get; set; }
        public string GERCRE { get; set; }
        public string ROL_APRO { get; set; }
    }
}
